### ISSUE TITLE
Make that license check a little smarter!

### ISSUE THREAD

**Issue by abscondment** [karan/add-a-license-please#5]
Not everyone puts their licensing information in a file starting with 'license'. Examples:

 * [Clojure](https://github.com/clojure/clojure) (and most EPL projects I've seen) use "epl-v10.html". Don't miss the "cpl-*" variant.
 * Many [repos](https://github.com/dxpdxp/graphviz) [just](https://github.com/justlostintime/gambas) [use](https://github.com/JaimeObregon/Geosantander.com) "COPYING"

I'm sure there are more.

**Comment by karan** [comment]
Very good suggestions! Will work on these.
